name: openfeature_dart_sdk_repository
description: Repository tooling for the OpenFeature Dart SDK packages.
publish_to: none

environment:
  sdk: ^3.12.2

dev_dependencies:
  git_hooks: ^1.0.2
  test: ^1.26.3

git_hooks:
  hooks:
    pre-commit: local_dev_tools/validate_commit.dart
    commit-msg: local_dev_tools/validate_commit_msg.dart
    pre-push: local_dev_tools/validate_branch.dart
