include: package:lints/recommended.yaml

linter:
  rules:
    avoid_dynamic_calls: true
    directives_ordering: true
    prefer_final_locals: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
